version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "06:00"
    timezone: Asia/Singapore
  open-pull-requests-limit: 30
  ignore:
  - dependency-name: typedoc
    versions:
    - 0.20.18
    - 0.20.20
    - 0.20.23
    - 0.20.24
    - 0.20.27
    - 0.20.28
    - 0.20.30
    - 0.20.32
    - 0.20.34
    - 0.20.35
  - dependency-name: "@commitlint/cli"
    versions:
    - 12.0.1
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.3
    - 5.2.0
  - dependency-name: "@commitlint/config-conventional"
    versions:
    - 12.0.1
  - dependency-name: graphql
    versions:
    - 15.4.0
